[Pre-Loader]: A better pre loader is added in the portfolio #110
SnowScriptWinterOfCode/PortfolioCreations pull request #112
Opened 2024-01-13 12:56 UTC by PranjaliBhardwaj

### Description
A better preloader is added , the colors are according to the portfolio color scheme and makes overall UI of webpage better. Pre loader is important and simple part of the webpage. The required code is added using simple HTML and CSS. as per the request. The task was to make a pre loader which aligns with the aesthetics of webpage. This design is new and makes it look beautiful as it is different from spinner pre loader which is very common.

### Changes Made
Changes are made in HTML tag in div and CSS with keyframes and required animations.

### Screenshots/Preview (if applicable)
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/146981751/9f6b77e7-df6f-4a68-9b3d-fc5438b1b919)

2024-01-13 12:59 UTC, PranjaliBhardwaj commented
IN URL you are seeing signupfs, is actually i copy the code in my html to test, so this is the test page screenshot but this is how that pre loader looks. This screenshot is just for providing the looks of the Preloader. I have also checked it twice it works pretty well.

2024-01-14 06:44 UTC, ayushichoudhary-19 requested changes

2024-01-14 06:44 UTC, ayushichoudhary-19 commented on styles.css
> +html, body {
Implementing these properties globally in the HTML and body substantially disrupts the main website. The scroll functionality is being hindered, and the application of 'display: flex' is causing displacement of elements from their current positions.

2024-01-14 06:49 UTC, ayushichoudhary-19 commented
Hey @PranjaliBhardwaj, the loader in the screenshot looks great. However, there are merge conflicts that need to be resolved. Also, your code seems to have an issue, as highlighted above. Please make the requested changes soon.

2024-01-14 07:29 UTC, closed without merging