issue #6 addinng skills section
SnowScriptWinterOfCode/PortfolioCreations pull request #27
Opened 2023-12-30 11:10 UTC by aarushisingh2004

As per the the issue allotted to me, issue  #6 
 I had to make the 
->skills
->testimonials
->faq section 

Out of which, I have completed skills section,  for further sections ill send the pull request again ,please review my pr
The added section of skills look like:-
![skill1](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/120239056/43ef527b-90e7-466d-94e1-7d00d48fda38)
![skill2](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/120239056/f4051d49-60a6-483c-a7d4-82940801fef0)

2023-12-30 13:49 UTC, aarushisingh2004 commented
#6  issue assigned to me, skills section added please review  @i-am-SnehaChauhan

2024-01-01 14:19 UTC, ayushichoudhary-19 commented on index.html
> +                    <li><a href="#Skills">Skills</a></li>
Let's maintain consistency. Could we keep the first letter of the ID name in lowercase, as in "#skills" and not "#Skills"? And the same goes for others too.

2024-01-01 14:21 UTC, ayushichoudhary-19 commented on index.html
> +        <section class="skills">
For the navbar link to work, we need to add `id="skills"` within this tag. Could you please incorporate that?

2024-01-01 14:25 UTC, ayushichoudhary-19 requested changes
Please review the comments added to your committed code and incorporate the changes. Thank you!

2024-01-01 16:20 UTC, aarushisingh2004 commented
ok I will make the changes soon

2024-01-01 17:45 UTC, aarushisingh2004 commented
please review @ayushichoudhary-19  I changed it to skill_section  and added skill_section to id , I kept the class name as "skill" only because I was using this class in css at many places , so to avoid mistake, please review , if any more changes are required

2024-01-01 20:20 UTC, aarushisingh2004 commented
please review @ayushichoudhary-19  , I have merged all conflicts and added changes suggested

2024-01-02 06:37 UTC, ayushichoudhary-19 approved these changes

2024-01-02 06:40 UTC, ayushichoudhary-19 commented
Great job, @aarushisingh2004! Your pull request looks good and I'll be merging it now!

2024-01-02 06:40 UTC, merged